reviews_trg: 'data/preprocessed/1pct/'
details_trg: 'data/preprocessed/1pct/'
posters_trg: 'data/processed/1pct/posters/'
reviews_src: 'data/raw/reviews/1pct/'
details_src: 'data/raw/details/1pct/'
posters_src: 'data/processed/1pct/posters/'