id:
  dir: 'data/raw/identifiers/1pct'
  genres: 'all'
  n_titles: null
  pct_titles: 1
  min_delay: 0.2
  max_delay: 0.3
  log_file: 'data_collection/identifiers.log'
  level: 'INFO'
  dir: 'logs' 
  msg_format: '%(asctime)s %(levelname)s %(message)s'
  dt_format: '%Y-%m-%d %H:%M:%S'

reviews:
  dir: 'data/raw/reviews/1pct/'
  id_dir: 'data/raw/identifiers/1pct/'
  genres: 'all'
  n_reviews: null
  pct_reviews: 10
  min_delay: 0.1
  max_delay: 0.2
  log_file: 'data_collection/reviews.log'
  level: 'INFO'
  dir: 'logs' 
  msg_format: '%(asctime)s %(levelname)s %(message)s'
  dt_format: '%Y-%m-%d %H:%M:%S'  

details:
  dir: 'data/raw/details/1pct/'
  id_dir: 'data/raw/identifiers/1pct/'
  poster_dir: 'data/preprocessed/1pct/posters/'
  genres: 'all'
  min_delay: 0.1
  max_delay: 0.2
  log_file: 'data_collection/details.log'
  level: 'INFO'
  dir: 'logs' 
  msg_format: '%(asctime)s %(levelname)s %(message)s'
  dt_format: '%Y-%m-%d %H:%M:%S'

user_reviews:
  dir: 'data/raw/other_reviews'
  id_dir: 'data/raw/identifiers/1pct'
  min_delay: 1
  max_delay: 2
  log_file: 'data_collection/user_reviews.log'
  level: 'INFO'
  dir: 'logs' 
  msg_format: '%(asctime)s %(levelname)s %(message)s'
  dt_format: '%Y-%m-%d %H:%M:%S'