id:
  bucket: 'movie-on-friday'
  metadata_file: 'metadata/metadata.json'
  genres: 'all'
  n_titles: null
  pct_titles: 10
  sleep_time: 0.2
  log_file: 'logs/imdb_parser/identifiers.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'

metadata:
  bucket: 'movie-on-friday'
  metadata_file: 'metadata/metadata.json'
  genres: 'all'
  chunk_size: 1000
  sleep_time: 0.2
  log_file: 'logs/imdb_parser/details.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'

reviews:
  bucket: 'movie-on-friday'
  metadata_file: 'metadata/metadata.json'
  review_folder: 'reviews'
  n_reviews: null
  pct_reviews: 200
  sleep_time: 0.1
  log_file: 'logs/imdb_parser/reviews.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'  
