id:
  metadata_file: 'data/metadata/metadata.json'
  genres: 'all'
  n_titles: null
  pct_titles: 10
  min_delay: 0.2
  max_delay: 0.3
  log_file: 'logs/imdb_parser/identifiers.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'

metadata:
  metadata_file: 'data/metadata/metadata.json'
  genres: 'all'
  min_delay: 0.1
  max_delay: 0.2
  log_file: 'logs/imdb_parser/details.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'

reviews:
  metadata_file: 'data/metadata/metadata.json'
  id_dir: 'data/raw/identifiers/1pct/'
  genres: 'all'
  n_reviews: null
  pct_reviews: 10
  min_delay: 0.1
  max_delay: 0.2
  log_file: 'logs/imdb_parser/reviews.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'  
