id:
  mode: 'cloud'
  metadata_file: 'metadata/metadata.json'
  genres: 'all'
  n_titles: null
  pct_titles: 10
  sleep_time: 0.2
  log_file: 'logs/imdb_parser/identifiers.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'

metadata:
  mode: 'cloud'
  metadata_file: 'metadata/metadata.json'
  chunk_size: 1000
  sleep_time: 0.2
  log_file: 'logs/imdb_parser/details.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'

reviews:
  mode: 'cloud'
  metadata_file: 'metadata/metadata.json'
  n_reviews: null
  chunk_size: 200
  pct_reviews: 100
  sleep_time: 0.1
  log_file: 'logs/imdb_parser/reviews.log'
  log_level: 'INFO'
  log_msg_format: '%(asctime)s %(levelname)s %(message)s'
  log_dt_format: '%Y-%m-%d %H:%M:%S'  

etl:
  mode: 'cloud'
  metadata_source: 'metadata/metadata.json'
  metadata_target: 'metadata/metadata_features.json'
  reviews_num_partitions: 10
  reviews_partition_format: 'parquet'