id_extraction:
  version: 1
  html_path: None
  id_path: None 
  min_delay: 3
  max_delay: 5
  genres: all
  n_titles: 500
  logger_cfg:
    filename:
    msg_format: '%(asctime)s %(message)s'
    dt_format: '%Y-%m-%d %H:%M:%S'
    level: 20
review_extraction:
  - 1
details_extraction:
  - 1
  