id_extraction:
  version: 1
  html_path: None
  id_path: None 
  genres: all
  n_titles: 500
  logger_cfg:
    filename:
    msg_format: '%(asctime)s %(message)s'
    dt_format: '%Y-%m-%d %H:%M:%S'
    level: 20
  request_delay:
    min_delay: 0.5
    max_delay: 1
review_extraction:
  request_delay:
    min_delay: 1
    max_delay: 2
details_extraction:
  request_delay:
    min_delay: 1
    max_delay: 2
  