data_collection:
  logger:
    level: 'INFO'
    dir: 'logs/data_collection' 
    msg_format: '%(asctime)s %(levelname)s %(message)s'
    dt_format: '%Y-%m-%d %H:%M:%S'

  id:
    dir: 'data/raw/identifiers/1pct'
    log_file: 'identifiers.log'
    genres: 'all'
    n_titles: null
    pct_titles: 1
    request_delay:
      min_delay: 0.2
      max_delay: 0.3

  reviews:
    dir: 'data/raw/reviews/1pct_10pct/'
    id_dir: 'data/raw/identifiers/1pct/'
    log_file: 'reviews.log'
    genres:
      - film-noir
      - history
      - horror
      - music
      - mystery
      - romance
      - sci-fi
      - sport
      - thriller
      - war
      - western
    n_reviews: null
    pct_reviews: 10
    request_delay:
      min_delay: 0.1
      max_delay: 0.2

  details:
    dir: 'data/raw/details/'
    id_dir: 'data/raw/identifiers/'
    request_delay:
      min_delay: 1
      max_delay: 2
    log_dir: 'details.log'

  user_reviews:
    dir: 'data/raw/other_reviews'
    request_delay:
      min_delay: 1
      max_delay: 2
    log_dir: 'other_reviews.log'

model_training:
  batch_size: 100
  batch_num: 2

model_inference:
  delay: None

application:
  model_name: default
  delay: None