logger:
  level: 'INFO'
  dir: 'logs' 
  msg_format: '%(asctime)s %(levelname)s %(message)s'
  dt_format: '%Y-%m-%d %H:%M:%S'

data_collection:
  logger:
    level: 'INFO'
    dir: 'logs/data_collection' 
    msg_format: '%(asctime)s %(levelname)s %(message)s'
    dt_format: '%Y-%m-%d %H:%M:%S'

  id:
    dir: 'data/raw/identifiers/1pct'
    log_file: 'identifiers.log'
    genres: 'all'
    n_titles: null
    pct_titles: 1
    request_delay:
      min_delay: 0.2
      max_delay: 0.3

  reviews:
    dir: 'data/raw/reviews/1pct_10pct/'
    id_dir: 'data/raw/identifiers/1pct/'
    log_file: 'reviews.log'
    genres: 'all'
    n_reviews: null
    pct_reviews: 10
    request_delay:
      min_delay: 0.1
      max_delay: 0.2

  details:
    dir: 'data/raw/details/1pct/'
    id_dir: 'data/raw/identifiers/1pct/'
    log_file: 'details.log'
    genres: 'all'
    request_delay:
      min_delay: 1
      max_delay: 2

  user_reviews:
    dir: 'data/raw/other_reviews'
    request_delay:
      min_delay: 1
      max_delay: 2
    log_dir: 'other_reviews.log'

training:
  batch_size: 100
  batch_num: 2

inference:
  model: 'recsys.models.thegodfather_model.TheGodfatherModel'
  model_params: null
  preprocessor: 'recsys.core.data.IdentityDataTransformer'
  preprocessor_params: null
  postprocessor: 'recsys.core.data.IdentityDataTransformer'
  postprocessor_params: null
  metadata_loader: null
  metadata_path: null
  log_file: 'app/inference.log' 

application:
  model_name: default
  delay: None