# Contains all relevant data to reproduce project:
# 0. [logger] - general configuration of logger used in each
#    of the following steps.
# 1. [data collection] - parsing imdb web-site to extract and
#    save data of movies' identifiers, reviews, details, etc.
# 2. [etl] - processing row data collected at previous step.
# 3. [training] - model training step.
# 4. [application] - model configuration for inference in
#    production and user interface
# 
# Note:
# * All directories (with _dir postfix) must be set up as we currently
#   in the root directory, except logger. In case of logger paths provided
#   are from root/logs/
logger:
  level: 'INFO'
  dir: 'logs' 
  msg_format: '%(asctime)s %(levelname)s %(message)s'
  dt_format: '%Y-%m-%d %H:%M:%S'

data_collection:
  id:
    dir: 'data/raw/identifiers/1pct'
    log_file: 'data_collection/identifiers.log'
    genres: 'all'
    n_titles: null
    pct_titles: 1
    request_delay:
      min_delay: 0.2
      max_delay: 0.3

  reviews:
    dir: 'data/raw/reviews/1pct/'
    id_dir: 'data/raw/identifiers/1pct/'
    log_file: 'data_collection/reviews.log'
    genres: 'all'
    n_reviews: null
    pct_reviews: 10
    request_delay:
      min_delay: 0.1
      max_delay: 0.2

  details:
    dir: 'data/raw/details/1pct/'
    id_dir: 'data/raw/identifiers/1pct/'
    poster_dir: 'data/preprocessed/1pct/posters/'
    log_file: 'data_collection/details.log'
    genres: 'all'
    request_delay:
      min_delay: 0.1
      max_delay: 0.2

  user_reviews:
    dir: 'data/raw/other_reviews'
    id_dir: 'data/raw/identifiers/1pct'
    log_file: 'data_collection/user_reviews.log'
    request_delay:
      min_delay: 1
      max_delay: 2

etl:
  reviews_trg: 'data/preprocessed/1pct/'
  details_trg: 'data/preprocessed/1pct/'
  posters_trg: 'data/processed/1pct/posters/'
  reviews_src: 'data/raw/reviews/1pct/'
  details_src: 'data/raw/details/1pct/'
  posters_src: 'data/processed/1pct/posters/'

model_training:
  model: null
  model_params: null
  model_dir: 'trained_models/'
  data_dir: 'data/preprocessed/1pct/'
  preprocessor: 'recsys.core.data.IdentityDataTransformer'
  preprocessor_params: null
  postprocessor: 'recsys.core.data.IdentityDataTransformer'
  postprocessor_params: null


application:
  model_inference:
    model: 'recsys.models.thegodfather_model.TheGodfatherModel'
    model_params: null
    model_params_path: null
    preprocessor: 'recsys.core.data.IdentityDataTransformer'
    preprocessor_params: null
    postprocessor: 'recsys.core.data.IdentityDataTransformer'
    postprocessor_params: null
    metadata_loader: 'recsys.core.data.CSVDataLoader'
    metadata_file: 'data/preprocessed/1pct/details.parquet'
    log_file: 'app/inference.log' 

  user_interface:
    interface: 'CLI'